.create-merge table RawEvents(
    GatewayId:string,
    MessageId:string,
    MessageTimestamp:datetime,
    Events:dynamic)

.alter-merge table RawEvents policy ingestionbatching
```
{
    "MaximumBatchingTimeSpan" : "00:00:30",
    "MaximumRawDataSizeMB": 1024
}
```

.alter-merge table RawEvents policy retention softdelete = 2h recoverability = disabled

.alter table RawEvents policy caching hot = 2h